### ISSUE TITLE
App Template 3 won't build inside a Nix sandbox

### ISSUE THREAD

**Issue by Goorzhel** [farcaller/nixhelm#18]
It does JSON schema validation using [a web `$ref`](https://github.com/bjw-s/helm-charts/blob/2a8fad90014b4bfa7eb6fb8efebacae70631d906/charts/other/app-template/values.schema.json), frustrating attempts to build it inside a sandbox.

I have a vague idea for a workaround, which is to munge the source repo ...
```nix
mkDerivation {
  src = fetchFromGitHub {...}
  buildPhase = ''
    cp -r $src $out
    cp -rf $out/charts/library/common/*schema* \
           $out/charts/other/app-template
  '';
}
```
... and special-case the chart somewhere in `nixhelm`, but I haven't found a non-ugly way to do that. So I've filed this as a placeholder until I figure it out.

**Comment by Goorzhel** [comment]
Helm 3.16.0 will [fix this](https://github.com/helm/helm/pull/12743).

**Comment by farcaller** [comment]
I think we're at 3.16.2 in nixpkgs now. Is it still an issue @Goorzhel ?

**Comment by Goorzhel** [comment]
Nope: `kubelib.buildHelmChart {extraOpts = ["--skip-schema-validation"]; ...}` should suffice.

I would have preferred not to discard schema validation entirely, but I can't justify the effort to make it work with this case alone. If more cases appear, I could set about adding a [`buildPhase`](https://github.com/farcaller/nix-kube-generators/blob/2be4f3cb99e179d9f94e6c8723862421437f8efb/lib/default.nix#L49) for post-download processing. Until then, this issue has no more gas in it.

**Comment by Goorzhel** [comment]
> I would have preferred not to discard schema validation entirely

And I [no longer will have to](https://github.com/bjw-s/helm-charts/releases/tag/app-template-3.7.1):

> Values schema is now dereferenced before packaging so it no longer relies on internet connectivity to validate the schema.

That said, the 3.7.1 tag [changed](https://github.com/bjw-s/helm-charts/commit/77ab223e7ed843b9305dd7892ff1382d858a81bb) sometime after its first publication, so I'll send a PR to update the hash.
